### ISSUE TITLE
SSL Certificate doesn't work on some older mobile browsers

### ISSUE THREAD

**Issue by brad** [MayOneUS/pledgeservice#12] opened 2014-05-05 05:27 UTC
Not sure how pervasive this is. I witnessed it on an old phone running Android 2.3.4 in the stock browser. On the same phone the site loads fine in Firefox.
The URL in question is https://pledge.mayone.us/pledge
![shot_2014-05-04_22-16-47](https://cloud.githubusercontent.com/assets/1614/2875300/928e914c-d415-11e3-9b24-cafb7cc9a5d9.png)

**Comment by hjfreyer** [comment] 2014-05-05 13:38
Duplicate of https://github.com/MayOneUS/app-engine/issues/14

**Closed as completed by hjfreyer** 2014-05-05 13:38 UTC

**Comment by hjfreyer** [comment] 2014-05-05 16:41
We're thinking this isn't actually a duplicate of the other issue, but in the absence of other people having issues, I'm okay assuming this is a symptom of code rot on a no longer supported phone.
